#!/bin/sh
if [ ! -d $SNAP_COMMON/hlsserver.conf ]; then
    cp $SNAP/hlsserver/hlsserver_snap.conf $SNAP_COMMON/hlsserver.conf
fi
mkdir -p $SNAP_COMMON/www/ && cp -R $SNAP/hlsserver/www/* $SNAP_COMMON/www/
